export const NICHE_CATEGORY_MAP: Record<string, number> = {
  tech: 1,
  security: 2,
  gaming: 3,
  education: 4,
  networking: 5,
  developer: 6,
  research: 7,
  ai: 8,
  innovation: 9,
};

export type RoadmapFeatureSeed = {
  featureId: string;
  contentSlug: string;
  name: string;
  tagline: string;
  description: string;
  category: keyof typeof NICHE_CATEGORY_MAP;
  tags: string[];
  schemaType: string;
  focusKeyword: string;
  metaTitle: string;
  seoDescription: string;
  isPremium?: boolean;
};

export const ROADMAP_PHASES: Array<{ phase: number; title: string; features: RoadmapFeatureSeed[] }> = [
  {
    phase: 1,
    title: "Core Platforms",
    features: [
      {
        featureId: "ai-pulse-full",
        contentSlug: "ai-pulse-activation",
        name: "AI Pulse",
        tagline: "Compare every AI model in real time",
        description: "Track major AI model releases and compare benchmarks, pricing, and performance.",
        category: "ai",
        tags: ["ai", "benchmarks", "comparisons"],
        schemaType: "SoftwareApplication",
        focusKeyword: "AI model comparison tool",
        metaTitle: "AI Pulse — Compare Every AI Model in Real Time | The Grid Nexus",
        seoDescription:
          "Track GPT-5, Claude 4, Gemini, LLaMA releases in real time. Compare AI model benchmarks, pricing, and performance.",
      },
      {
        featureId: "breach-sim",
        contentSlug: "breach-sim-interactive",
        name: "Breach Sim",
        tagline: "Interactive cybersecurity training simulator",
        description: "Practice defending against ransomware, phishing, SQL injection, and zero-day exploits in a safe sandbox.",
        category: "security",
        tags: ["training", "simulator", "incident-response"],
        schemaType: "LearningResource",
        focusKeyword: "cybersecurity breach simulation platform",
        metaTitle: "Breach Sim — Interactive Cybersecurity Training Simulator | Grid Nexus",
        seoDescription:
          "Practice defending against real-world attacks in a browser-based sandbox with scenario-driven learning.",
      },
      {
        featureId: "security-score",
        contentSlug: "security-score-platform",
        name: "Security Score",
        tagline: "Free website security rating and scanner",
        description: "Scan domains for SSL/TLS, DNS weaknesses, CVEs, and compliance gaps.",
        category: "security",
        tags: ["scanner", "ssl", "dns", "cve"],
        schemaType: "WebApplication",
        focusKeyword: "website security score checker",
        metaTitle: "Security Score — Free Website Security Rating & Vulnerability Scanner | Grid Nexus",
        seoDescription:
          "Instantly scan any domain and get a security score with actionable remediation steps.",
      },
      {
        featureId: "threat-dashboard",
        contentSlug: "live-threat-dashboard",
        name: "Live Threat Dashboard",
        tagline: "Real-time global cyber attack map",
        description: "Watch cyber attacks unfold globally and track active ransomware and CVE exploitation.",
        category: "security",
        tags: ["threat-intel", "live", "dashboard"],
        schemaType: "WebApplication",
        focusKeyword: "live cyber attack map real-time",
        metaTitle: "Live Threat Dashboard — Real-Time Global Cyber Attack Map | Grid Nexus",
        seoDescription:
          "Track global threats, ransomware campaigns, and active exploitation on an interactive dashboard.",
      },
      {
        featureId: "gaming-hub",
        contentSlug: "gaming-hub-community",
        name: "Gaming Hub",
        tagline: "Games database + esports tracker + deals",
        description: "Track games, follow esports, find deals, and read community walkthroughs.",
        category: "gaming",
        tags: ["esports", "deals", "database"],
        schemaType: "WebSite",
        focusKeyword: "gaming news esports database 2026",
        metaTitle: "Gaming Hub — Games Database, Esports Tracker & Best Game Deals | Grid Nexus",
        seoDescription:
          "Track games, tournaments, deals, and guides in a single gaming platform.",
      },
    ],
  },
  {
    phase: 2,
    title: "Community & Intelligence",
    features: [
      {
        featureId: "roadmap-interactive",
        contentSlug: "roadmap",
        name: "Interactive Roadmap",
        tagline: "Public roadmap with community voting",
        description: "A transparent, community-driven product roadmap with live voting and discussion.",
        category: "innovation",
        tags: ["roadmap", "voting", "community"],
        schemaType: "WebPage",
        focusKeyword: "public product roadmap with community voting",
        metaTitle: "Product Roadmap | Vote on Features | The Grid Nexus",
        seoDescription: "Shape the future of The Grid Nexus by voting on upcoming features.",
      },
      {
        featureId: "nexus-intelligence",
        contentSlug: "nexus-intelligence",
        name: "Nexus Intelligence",
        tagline: "AI-powered tech news curation",
        description: "Personalized intelligence feed across tech, security, and gaming.",
        category: "ai",
        tags: ["personalization", "curation", "ai"],
        schemaType: "SoftwareApplication",
        focusKeyword: "AI-powered tech news curation",
        metaTitle: "Nexus Intelligence — AI-Powered Tech News Curation | The Grid Nexus",
        seoDescription: "AI-driven curation that keeps you ahead across tech, security and gaming.",
      },
      {
        featureId: "nexus-academy",
        contentSlug: "nexus-academy-platform",
        name: "Nexus Academy",
        tagline: "Courses and certifications with labs",
        description: "Learn cybersecurity, AI engineering, and game dev with hands-on labs and certifications.",
        category: "education",
        tags: ["courses", "labs", "certification"],
        schemaType: "EducationalOrganization",
        focusKeyword: "online cybersecurity AI certification 2026",
        metaTitle: "Nexus Academy — Cybersecurity, AI & Game Dev Courses | Grid Nexus",
        seoDescription: "Hands-on labs and certifications for cybersecurity, AI and game development.",
      },
    ],
  },
  {
    phase: 3,
    title: "2026 Security and Gaming Intelligence",
    features: [
      {
        featureId: "rdm-ai-threat-detection",
        contentSlug: "ai-driven-threat-detection-response-2026-cybersecurity-roadmap",
        name: "AI-Driven Threat Detection and Response",
        tagline: "The 2026 cybersecurity roadmap for modern SOC teams",
        description: "How ML, SOAR automation, and anomaly detection reshape enterprise security response.",
        category: "security",
        tags: ["ai", "soc", "soar"],
        schemaType: "Article",
        focusKeyword: "AI-driven threat detection and response",
        metaTitle: "AI-Driven Threat Detection & Response 2026 | Cybersecurity Roadmap",
        seoDescription: "Discover how AI-powered threat detection, automated incident response, and SOAR systems are transforming cybersecurity in 2026.",
      },
      {
        featureId: "rdm-zero-trust-intelligence",
        contentSlug: "zero-trust-architecture-intelligence-2026-roadmap",
        name: "Zero Trust Architecture Intelligence in 2026",
        tagline: "From buzzword to operational backbone",
        description: "Identity-centric risk scoring and policy-as-code become core cloud security controls.",
        category: "security",
        tags: ["zero-trust", "identity", "policy-as-code"],
        schemaType: "Article",
        focusKeyword: "Zero Trust Architecture intelligence 2026",
        metaTitle: "Zero Trust Architecture (ZTA) Intelligence 2026 | Security Roadmap Guide",
        seoDescription: "Explore how Zero Trust Architecture is evolving into a full intelligence layer in 2026.",
      },
      {
        featureId: "rdm-ai-anti-cheat",
        contentSlug: "ai-enhanced-game-security-anti-cheat-machine-learning-2026",
        name: "AI-Enhanced Game Security and Anti-Cheat",
        tagline: "Machine learning versus modern cheating ecosystems",
        description: "Behavioral ML and federated learning strengthen anti-cheat and fraud detection in gaming.",
        category: "gaming",
        tags: ["anti-cheat", "ml", "fraud"],
        schemaType: "Article",
        focusKeyword: "AI-enhanced game security anti-cheat 2026",
        metaTitle: "AI-Enhanced Game Security & Anti-Cheat 2026 | ML-Powered Gaming Protection",
        seoDescription: "Learn how AI and machine learning are revolutionizing anti-cheat systems in 2026.",
      },
      {
        featureId: "rdm-llm-soc",
        contentSlug: "generative-ai-cybersecurity-llm-soc-automation-2026",
        name: "Generative AI for Cybersecurity SOC Operations",
        tagline: "How LLMs are transforming triage and response",
        description: "From alert triage to playbook generation, with guardrails for hallucination risk.",
        category: "security",
        tags: ["llm", "soc", "automation"],
        schemaType: "Article",
        focusKeyword: "generative AI cybersecurity LLM SOC automation",
        metaTitle: "Generative AI for Cybersecurity 2026 | LLM SOC Automation & Threat Intel",
        seoDescription: "Explore how generative AI and LLMs are transforming cybersecurity SOC operations in 2026.",
      },
      {
        featureId: "rdm-ctem",
        contentSlug: "ai-driven-continuous-threat-exposure-management-ctem-2026",
        name: "AI-Driven CTEM",
        tagline: "Continuous Threat Exposure Management in 2026",
        description: "Risk-scored, continuous exposure prioritization across cloud, SaaS, and on-prem assets.",
        category: "security",
        tags: ["ctem", "vulnerability", "exposure"],
        schemaType: "Article",
        focusKeyword: "AI-driven Continuous Threat Exposure Management CTEM 2026",
        metaTitle: "AI-Driven CTEM 2026 | Continuous Threat Exposure Management Roadmap",
        seoDescription: "Understand how AI-driven CTEM is replacing traditional vulnerability management in 2026.",
      },
      {
        featureId: "rdm-ai-risk-governance",
        contentSlug: "secure-ai-risk-governance-trustworthy-ai-trism-2026",
        name: "Secure AI and AI Risk Governance",
        tagline: "Trustworthy AI controls that work in production",
        description: "TRiSM-style frameworks, drift monitoring, and explainability dashboards for enterprise AI.",
        category: "tech",
        tags: ["ai-governance", "trism", "compliance"],
        schemaType: "Article",
        focusKeyword: "AI risk governance trustworthy AI TRiSM 2026",
        metaTitle: "AI Risk Governance & Trustworthy AI TRiSM 2026 | Secure AI Roadmap",
        seoDescription: "Discover how AI risk governance frameworks are helping enterprises secure AI systems in 2026.",
      },
      {
        featureId: "rdm-cloud-native-security",
        contentSlug: "cloud-native-security-intelligence-cspm-cwpp-2026",
        name: "Cloud-Native Security Intelligence",
        tagline: "CSPM + CWPP for multi-cloud protection",
        description: "Automated drift detection, Kubernetes coverage, and IAM intelligence for cloud security.",
        category: "security",
        tags: ["cspm", "cwpp", "multi-cloud"],
        schemaType: "Article",
        focusKeyword: "cloud-native security intelligence CSPM CWPP 2026",
        metaTitle: "Cloud-Native Security CSPM CWPP 2026 | Multi-Cloud Security Intelligence",
        seoDescription: "Explore cloud-native security intelligence in 2026 across CSPM, CWPP, and multi-cloud operations.",
      },
      {
        featureId: "rdm-identity-passwordless",
        contentSlug: "identity-centric-security-passwordless-auth-2026-roadmap",
        name: "Identity-Centric Security and Passwordless Auth",
        tagline: "Passkeys and risk-based access in 2026",
        description: "FIDO passkeys, biometrics, and dynamic risk scoring redefine identity security programs.",
        category: "security",
        tags: ["identity", "passkeys", "rba"],
        schemaType: "Article",
        focusKeyword: "identity-centric security passwordless authentication 2026",
        metaTitle: "Identity-Centric Security & Passwordless Auth 2026 | FIDO Passkeys Roadmap",
        seoDescription: "Learn how identity-centric security and passwordless authentication are transforming access management.",
      },
      {
        featureId: "rdm-game-account-security",
        contentSlug: "game-account-security-anti-phishing-2026-gaming-platforms",
        name: "Game-Account Security and Anti-Phishing",
        tagline: "How platforms protect players in 2026",
        description: "Login anomaly detection, device fingerprinting, and in-game fraud warnings for account defense.",
        category: "gaming",
        tags: ["accounts", "anti-phishing", "fraud"],
        schemaType: "Article",
        focusKeyword: "game account security anti-phishing 2026 gaming platforms",
        metaTitle: "Game Account Security & Anti-Phishing 2026 | Gaming Platform Protection",
        seoDescription: "Explore how gaming platforms are defending against phishing and credential theft in 2026.",
      },
      {
        featureId: "rdm-threat-intel-proactive",
        contentSlug: "threat-intelligence-proactive-defense-stix-taxii-2026",
        name: "Threat-Intelligence-Driven Proactive Defense",
        tagline: "Getting ahead of attackers with STIX/TAXII",
        description: "Automated IOC enrichment and AI-powered threat hunting move teams beyond reactive security.",
        category: "security",
        tags: ["stix", "taxii", "threat-hunting"],
        schemaType: "Article",
        focusKeyword: "threat intelligence proactive defense STIX TAXII 2026",
        metaTitle: "Threat Intelligence Proactive Defense 2026 | STIX TAXII IOC Hunting Roadmap",
        seoDescription: "Learn how threat-intelligence-driven proactive defense is transforming cybersecurity strategies.",
      },
      {
        featureId: "rdm-awareness-training",
        contentSlug: "ai-enabled-security-awareness-training-adaptive-learning-2026",
        name: "AI-Enabled Security Awareness and Training",
        tagline: "Adaptive learning replaces annual checkboxes",
        description: "Adaptive phishing simulations and personalized micro-learning for measurable culture change.",
        category: "security",
        tags: ["awareness", "adaptive-learning", "phishing"],
        schemaType: "Article",
        focusKeyword: "AI security awareness training adaptive phishing simulation 2026",
        metaTitle: "AI Security Awareness Training 2026 | Adaptive Phishing Simulation & Micro-Learning",
        seoDescription: "Discover how AI-enabled security awareness programs are replacing static compliance training.",
      },
      {
        featureId: "rdm-devsecops",
        contentSlug: "secure-devops-devsecops-intelligence-cicd-2026",
        name: "Secure DevOps and DevSecOps Intelligence",
        tagline: "Embedding security into every CI/CD stage",
        description: "SAST, DAST, SBOM management, and AI risk scoring for secure software delivery.",
        category: "tech",
        tags: ["devsecops", "cicd", "sbom"],
        schemaType: "Article",
        focusKeyword: "DevSecOps intelligence CI/CD SBOM SAST DAST 2026",
        metaTitle: "DevSecOps Intelligence 2026 | Secure DevOps SAST DAST SBOM CI/CD Roadmap",
        seoDescription: "Learn how DevSecOps is evolving in 2026 with automated security controls in CI/CD pipelines.",
      },
      {
        featureId: "rdm-cheat-intel-layer",
        contentSlug: "game-cheating-exploit-detection-analytics-cheat-intelligence-2026",
        name: "Game Cheating and Exploit Detection Analytics",
        tagline: "Building the cheat-intelligence layer",
        description: "Statistical behavior models and telemetry correlation for anti-exploit detection in 2026.",
        category: "gaming",
        tags: ["cheating", "telemetry", "analytics"],
        schemaType: "Article",
        focusKeyword: "game cheating exploit detection analytics cheat intelligence 2026",
        metaTitle: "Game Cheating & Exploit Detection Analytics 2026 | Cheat Intelligence Layer",
        seoDescription: "Discover how publishers are building cheat-intelligence layers using behavior models and telemetry.",
      },
      {
        featureId: "rdm-digital-twin-security",
        contentSlug: "ai-driven-digital-twin-security-critical-systems-2026",
        name: "AI-Driven Digital Twin Security",
        tagline: "Simulating critical-system attacks before they happen",
        description: "Attack path simulation, what-if analysis, and safer remediation validation for critical systems.",
        category: "security",
        tags: ["digital-twin", "critical-infra", "simulation"],
        schemaType: "Article",
        focusKeyword: "AI digital twin security critical systems cyber-physical 2026",
        metaTitle: "AI Digital Twin Security 2026 | Critical Systems Cyber-Physical Protection",
        seoDescription: "Explore AI-driven digital twin security for industrial and cyber-physical environments in 2026.",
      },
      {
        featureId: "rdm-pets-confidential-ai",
        contentSlug: "privacy-enhancing-technologies-confidential-ai-federated-learning-2026",
        name: "Privacy-Enhancing Technologies and Confidential AI",
        tagline: "The 2026 roadmap for data-responsible intelligence",
        description: "Federated learning, homomorphic encryption, and differential privacy in real-world AI systems.",
        category: "tech",
        tags: ["privacy", "federated-learning", "confidential-ai"],
        schemaType: "Article",
        focusKeyword: "privacy-enhancing technologies PETs confidential AI federated learning 2026",
        metaTitle: "Privacy-Enhancing Technologies PETs Confidential AI 2026 | Federated Learning Roadmap",
        seoDescription: "Learn how PETs are enabling confidential AI for cybersecurity and gaming applications.",
      },
      {
        featureId: "rdm-metaverse-security",
        contentSlug: "secure-metaverse-virtual-world-infrastructure-security-intelligence-2026",
        name: "Secure Metaverse and Virtual World Infrastructure",
        tagline: "Security intelligence for digital realities",
        description: "Decentralized identity, asset provenance, and AI moderation for virtual world security.",
        category: "gaming",
        tags: ["metaverse", "identity", "moderation"],
        schemaType: "Article",
        focusKeyword: "secure metaverse virtual world security intelligence 2026",
        metaTitle: "Secure Metaverse & Virtual World Security 2026 | Avatar Identity NFT Fraud AI Moderation",
        seoDescription: "Explore how metaverse platforms are building security intelligence layers in 2026.",
      },
      {
        featureId: "rdm-edr-nextgen",
        contentSlug: "ai-driven-endpoint-device-security-intelligence-edr-2026",
        name: "AI-Driven Endpoint and Device Security Intelligence",
        tagline: "The next generation of EDR",
        description: "Behavioral baselining, fileless malware detection, and cross-endpoint attack correlation.",
        category: "security",
        tags: ["edr", "endpoint", "fileless-malware"],
        schemaType: "Article",
        focusKeyword: "AI-driven endpoint security device intelligence EDR 2026",
        metaTitle: "AI-Driven Endpoint Security EDR 2026 | Behavioral Baselining Fileless Malware",
        seoDescription: "Explore how AI-driven endpoint and device security intelligence is evolving EDR in 2026.",
      },
      {
        featureId: "rdm-game-fraud-monetization",
        contentSlug: "game-monetization-anti-fraud-intelligence-2026-in-app-purchases",
        name: "Game Monetization and Anti-Fraud Intelligence",
        tagline: "Protecting revenue without punishing players",
        description: "Chargeback scoring, device clustering, and account-farm detection for gaming economics.",
        category: "gaming",
        tags: ["fraud", "monetization", "chargebacks"],
        schemaType: "Article",
        focusKeyword: "game monetization anti-fraud intelligence 2026 in-app purchases",
        metaTitle: "Game Monetization Anti-Fraud Intelligence 2026 | In-App Purchase Chargeback Protection",
        seoDescription: "Discover anti-fraud intelligence strategies for gaming monetization in 2026.",
      },
      {
        featureId: "rdm-ai-game-balance",
        contentSlug: "secure-ai-assisted-game-design-balance-analytics-2026",
        name: "Secure AI-Assisted Game Design and Balance Analytics",
        tagline: "Building exploit-resistant game economies",
        description: "Economic simulators, exploit-drift monitoring, and AI-powered play-testing for resilient design.",
        category: "gaming",
        tags: ["game-design", "balance", "exploit-resistance"],
        schemaType: "Article",
        focusKeyword: "AI-assisted game design balance analytics exploit-resistant 2026",
        metaTitle: "AI-Assisted Game Design & Balance Analytics 2026 | Exploit-Resistant Economy Design",
        seoDescription: "Learn how AI-assisted design and analytics help developers build cheat-resistant game economies.",
      },
      {
        featureId: "rdm-cross-vertical-sharing",
        contentSlug: "cross-vertical-cybersecurity-intelligence-sharing-stix-misp-2026",
        name: "Cross-Vertical Cybersecurity Intelligence Sharing",
        tagline: "The collective defense ecosystem maturing in 2026",
        description: "How STIX, MISP, and federation models enable intelligence sharing across major sectors.",
        category: "security",
        tags: ["stix", "misp", "collective-defense"],
        schemaType: "Article",
        focusKeyword: "cross-vertical cybersecurity intelligence sharing STIX MISP 2026",
        metaTitle: "Cross-Vertical Cybersecurity Intelligence Sharing 2026 | STIX MISP Federation Roadmap",
        seoDescription: "Explore how cross-vertical intelligence sharing is creating collective defense in 2026.",
      },
    ],
  },
];
